### PR TITLE
Non-None default in toggle_state to mean "toggle"

### LINKED ISSUE #70: toggle_state default for active is error-prone
`toggle_state` takes an optional `active` param that lets you specify whether the state should be on or off, instead of it being switched from its previous value.  Having a default value of `None` is problematic because `None` can easily be mistaken for a "truthy" `False` when dealing with relation data, which leads to the state being unexpectedly set.  For example, the following breaks:

```python
conv.toggle_state('{relation_name}.feature_x',
                  active=conv.get_remote('feature_x_available'))
```

This can also be more subtle because `None and <anything>` returns `None` instead of `False` as one might expect.  For example, this also breaks:

```python
name = conv.get_remote('name')
version = conv.get_remote('version')
conv.toggle_state('{relation_name}.ready', name and version)
```

### PR DESCRIPTION
**Pull request by johnsca**
Fixes #70

### CODE REVIEW

**Comment by kwmonroe** [comment]
There was some chatter on #juju about not using a string representation for toggle (instead using `object()`).  I'm fine with this as-in, or with that changed.

**Comment by stub42** [comment]
This needs a test, which I suspect is trivial.

**Comment by johnsca** [comment]
Updated with `object()` and test.

**Comment by stub42** [comment]
:boat: :+1: :eggplant:

**Pull request merged**
