### PR TITLE
Hotfix for issue #161

### PR DESCRIPTION
**Pull request by galgalesh**
fixes https://github.com/juju-solutions/charms.reactive/issues/161

### CODE REVIEW

**Comment by johnsca** [comment]
```
/home/travis/build/juju-solutions/charms.reactive/tests/test_endpoints.py:92:52: W503 line break before binary operator
```

**Comment by galgalesh** [comment]
Thanks, fixed it.

Maybe we should add the `lint` target to the test target?

**Comment by johnsca** [comment]
Fine by me to combine them.

**Comment by johnsca** [comment]
This has been released in 0.6.2

**Pull request merged**
