### PR TITLE
Adjust PATH and PYTHONPATH to work around bundled deps

### PR DESCRIPTION
**Pull request by johnsca**
Because the deps in basic are installed into $CHARM_DIR/{lib,bin} and not at the system level, bash handlers will fail inside `charms.reactive.sh` without this work-around.

### CODE REVIEW

**Comment by marcoceppi** [comment]
LGTM, tested and working

**Comment by chuckbutler** [comment]
:+1:  I witnessed this work

**Comment by marcoceppi** [comment]
:boat:

**Comment by chuckbutler** [comment]
:cow: :boy:

**Comment by kat-co** [comment]
Thank you so much eco team :) :100:

**Pull request merged**
